logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced eXtended"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "apk"                                                   # 'both', 'apk' or 'module'
included-patches = "force-premium-heading"
excluded-patches = "change-homepage custom-branding-youtube-name custom-branding-icon-revancify-blue enable-new-splash-animation enable-new-thumbnail-preview enable-wide-search-bar hide-account-menu hide-autoplay-button hide-button-container hide-captions-button hide-category-bar hide-channel-avatar-section hide-comment-component hide-description-components hide-filmstrip-overlay hide-fullscreen-panels hide-handle hide-latest-videos-button hide-layout-components hide-load-more-button hide-mix-playlists hide-music-button hide-previous-next-button hide-quick-actions hide-trending-searches"                                                 # whitespace seperated list of patches to include
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"

[Music]
build-mode = "apk"
excluded-patches = "custom-branding-music-name custom-branding-icon-revancify-blue hide-category-bar hide-category-bar hide-new-playlist-button hide-playlist-card"
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
apkmirror-arch = "arm64-v8a"

[Reddit]
build-mode = "apk"
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
apkmirror-arch = "universal"
